name: Deploy-React
on:
  push:
    branches: main
    paths: "apps/cas-codes/**"
  pull_request:
    branches: main
    paths: "apps/cas-codes/**"

jobs:
  deploy:
    name: Deploy-React
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Copy env file
        run: "cp ./apps/cas-codes/.env.prod ./apps/cas-codes/.env"

      - name: Build step
        run: "deno task --cwd ./apps/cas-codes build"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "cas-codes"
          entrypoint: "jsr:@std/http/file-server"
          root: "./apps/cas-codes/dist"
